[package]
name = "guess_number"
version = "0.1.5"
edition = "2021"

[dependencies]
rand = "0.8.5"
dialoguer = "0.10.3"
bcrypt = "0.13.0"
csv = "1.3.0"
anyhow = "1.0.75"
once_cell = "1.19.0"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
